/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAvinCheckRouteImport } from './routes/_authenticated/avin-check'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAvinCheckIndexRouteImport } from './routes/_authenticated/avin-check/index'
import { Route as AuthenticatedAvinCheckBondRouteImport } from './routes/_authenticated/avin-check/bond'
import { Route as AuthenticatedAvinCheckBondWithdrawalsRouteImport } from './routes/_authenticated/avin-check/bond-withdrawals'
import { Route as AuthenticatedAvinCheckSupportReviewsRouteImport } from './routes/_authenticated/avin-check/support-reviews'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedDisputesIndexRouteImport } from './routes/_authenticated/disputes/index'
import { Route as AuthenticatedDisputesDisputeIdRouteImport } from './routes/_authenticated/disputes/$disputeId'
import { Route as AuthenticatedListingsIndexRouteImport } from './routes/_authenticated/listings/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedOperationsIndexRouteImport } from './routes/_authenticated/operations/index'
import { Route as AuthenticatedSellerApplicationsIndexRouteImport } from './routes/_authenticated/seller-applications/index'
import { Route as AuthenticatedSellerApplicationsApplicationIdRouteImport } from './routes/_authenticated/seller-applications/$applicationId'
import { Route as AuthenticatedSellersIndexRouteImport } from './routes/_authenticated/sellers/index'
import { Route as AuthenticatedSellersSellerIdRouteImport } from './routes/_authenticated/sellers/$sellerId'
import { Route as AuthenticatedWithdrawalsIndexRouteImport } from './routes/_authenticated/withdrawals/index'
import { Route as AuthenticatedAvinCheckProviderRevisionsIndexRouteImport } from './routes/_authenticated/avin-check/provider-revisions/index'
import { Route as AuthenticatedAvinCheckProviderRevisionsRevisionIdRouteImport } from './routes/_authenticated/avin-check/provider-revisions/$revisionId'
import { Route as AuthenticatedAvinCheckProvidersIndexRouteImport } from './routes/_authenticated/avin-check/providers/index'
import { Route as AuthenticatedAvinCheckProvidersApplicationIdRouteImport } from './routes/_authenticated/avin-check/providers/$applicationId'
import { Route as AuthenticatedAvinCheckRiskReportsIndexRouteImport } from './routes/_authenticated/avin-check/risk-reports/index'
import { Route as AuthenticatedAvinCheckRiskReportsReportIdRouteImport } from './routes/_authenticated/avin-check/risk-reports/$reportId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAvinCheckRoute = AuthenticatedAvinCheckRouteImport.update({
  id: '/avin-check',
  path: '/avin-check',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAvinCheckIndexRoute =
  AuthenticatedAvinCheckIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAvinCheckRoute,
  } as any)
const AuthenticatedAvinCheckBondRoute =
  AuthenticatedAvinCheckBondRouteImport.update({
    id: '/bond',
    path: '/bond',
    getParentRoute: () => AuthenticatedAvinCheckRoute,
  } as any)
const AuthenticatedAvinCheckBondWithdrawalsRoute =
  AuthenticatedAvinCheckBondWithdrawalsRouteImport.update({
    id: '/bond-withdrawals',
    path: '/bond-withdrawals',
    getParentRoute: () => AuthenticatedAvinCheckRoute,
  } as any)
const AuthenticatedAvinCheckSupportReviewsRoute =
  AuthenticatedAvinCheckSupportReviewsRouteImport.update({
    id: '/support-reviews',
    path: '/support-reviews',
    getParentRoute: () => AuthenticatedAvinCheckRoute,
  } as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDisputesIndexRoute =
  AuthenticatedDisputesIndexRouteImport.update({
    id: '/disputes/',
    path: '/disputes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDisputesDisputeIdRoute =
  AuthenticatedDisputesDisputeIdRouteImport.update({
    id: '/disputes/$disputeId',
    path: '/disputes/$disputeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListingsIndexRoute =
  AuthenticatedListingsIndexRouteImport.update({
    id: '/listings/',
    path: '/listings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationsIndexRoute =
  AuthenticatedOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSellerApplicationsIndexRoute =
  AuthenticatedSellerApplicationsIndexRouteImport.update({
    id: '/seller-applications/',
    path: '/seller-applications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSellerApplicationsApplicationIdRoute =
  AuthenticatedSellerApplicationsApplicationIdRouteImport.update({
    id: '/seller-applications/$applicationId',
    path: '/seller-applications/$applicationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSellersIndexRoute =
  AuthenticatedSellersIndexRouteImport.update({
    id: '/sellers/',
    path: '/sellers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSellersSellerIdRoute =
  AuthenticatedSellersSellerIdRouteImport.update({
    id: '/sellers/$sellerId',
    path: '/sellers/$sellerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWithdrawalsIndexRoute =
  AuthenticatedWithdrawalsIndexRouteImport.update({
    id: '/withdrawals/',
    path: '/withdrawals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAvinCheckProviderRevisionsIndexRoute =
  AuthenticatedAvinCheckProviderRevisionsIndexRouteImport.update({
    id: '/provider-revisions/',
    path: '/provider-revisions/',
    getParentRoute: () => AuthenticatedAvinCheckRoute,
  } as any)
const AuthenticatedAvinCheckProviderRevisionsRevisionIdRoute =
  AuthenticatedAvinCheckProviderRevisionsRevisionIdRouteImport.update({
    id: '/provider-revisions/$revisionId',
    path: '/provider-revisions/$revisionId',
    getParentRoute: () => AuthenticatedAvinCheckRoute,
  } as any)
const AuthenticatedAvinCheckProvidersIndexRoute =
  AuthenticatedAvinCheckProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => AuthenticatedAvinCheckRoute,
  } as any)
const AuthenticatedAvinCheckProvidersApplicationIdRoute =
  AuthenticatedAvinCheckProvidersApplicationIdRouteImport.update({
    id: '/providers/$applicationId',
    path: '/providers/$applicationId',
    getParentRoute: () => AuthenticatedAvinCheckRoute,
  } as any)
const AuthenticatedAvinCheckRiskReportsIndexRoute =
  AuthenticatedAvinCheckRiskReportsIndexRouteImport.update({
    id: '/risk-reports/',
    path: '/risk-reports/',
    getParentRoute: () => AuthenticatedAvinCheckRoute,
  } as any)
const AuthenticatedAvinCheckRiskReportsReportIdRoute =
  AuthenticatedAvinCheckRiskReportsReportIdRouteImport.update({
    id: '/risk-reports/$reportId',
    path: '/risk-reports/$reportId',
    getParentRoute: () => AuthenticatedAvinCheckRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof SignInRoute
  '/two-factor': typeof TwoFactorRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/avin-check': typeof AuthenticatedAvinCheckRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/avin-check/bond': typeof AuthenticatedAvinCheckBondRoute
  '/avin-check/bond-withdrawals': typeof AuthenticatedAvinCheckBondWithdrawalsRoute
  '/avin-check/support-reviews': typeof AuthenticatedAvinCheckSupportReviewsRoute
  '/disputes/$disputeId': typeof AuthenticatedDisputesDisputeIdRoute
  '/seller-applications/$applicationId': typeof AuthenticatedSellerApplicationsApplicationIdRoute
  '/sellers/$sellerId': typeof AuthenticatedSellersSellerIdRoute
  '/avin-check/': typeof AuthenticatedAvinCheckIndexRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/disputes/': typeof AuthenticatedDisputesIndexRoute
  '/listings/': typeof AuthenticatedListingsIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/operations/': typeof AuthenticatedOperationsIndexRoute
  '/seller-applications/': typeof AuthenticatedSellerApplicationsIndexRoute
  '/sellers/': typeof AuthenticatedSellersIndexRoute
  '/withdrawals/': typeof AuthenticatedWithdrawalsIndexRoute
  '/avin-check/provider-revisions/$revisionId': typeof AuthenticatedAvinCheckProviderRevisionsRevisionIdRoute
  '/avin-check/providers/$applicationId': typeof AuthenticatedAvinCheckProvidersApplicationIdRoute
  '/avin-check/risk-reports/$reportId': typeof AuthenticatedAvinCheckRiskReportsReportIdRoute
  '/avin-check/provider-revisions/': typeof AuthenticatedAvinCheckProviderRevisionsIndexRoute
  '/avin-check/providers/': typeof AuthenticatedAvinCheckProvidersIndexRoute
  '/avin-check/risk-reports/': typeof AuthenticatedAvinCheckRiskReportsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/two-factor': typeof TwoFactorRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/avin-check/bond': typeof AuthenticatedAvinCheckBondRoute
  '/avin-check/bond-withdrawals': typeof AuthenticatedAvinCheckBondWithdrawalsRoute
  '/avin-check/support-reviews': typeof AuthenticatedAvinCheckSupportReviewsRoute
  '/disputes/$disputeId': typeof AuthenticatedDisputesDisputeIdRoute
  '/seller-applications/$applicationId': typeof AuthenticatedSellerApplicationsApplicationIdRoute
  '/sellers/$sellerId': typeof AuthenticatedSellersSellerIdRoute
  '/avin-check': typeof AuthenticatedAvinCheckIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/disputes': typeof AuthenticatedDisputesIndexRoute
  '/listings': typeof AuthenticatedListingsIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/operations': typeof AuthenticatedOperationsIndexRoute
  '/seller-applications': typeof AuthenticatedSellerApplicationsIndexRoute
  '/sellers': typeof AuthenticatedSellersIndexRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsIndexRoute
  '/avin-check/provider-revisions/$revisionId': typeof AuthenticatedAvinCheckProviderRevisionsRevisionIdRoute
  '/avin-check/providers/$applicationId': typeof AuthenticatedAvinCheckProvidersApplicationIdRoute
  '/avin-check/risk-reports/$reportId': typeof AuthenticatedAvinCheckRiskReportsReportIdRoute
  '/avin-check/provider-revisions': typeof AuthenticatedAvinCheckProviderRevisionsIndexRoute
  '/avin-check/providers': typeof AuthenticatedAvinCheckProvidersIndexRoute
  '/avin-check/risk-reports': typeof AuthenticatedAvinCheckRiskReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/two-factor': typeof TwoFactorRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/avin-check': typeof AuthenticatedAvinCheckRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/avin-check/bond': typeof AuthenticatedAvinCheckBondRoute
  '/_authenticated/avin-check/bond-withdrawals': typeof AuthenticatedAvinCheckBondWithdrawalsRoute
  '/_authenticated/avin-check/support-reviews': typeof AuthenticatedAvinCheckSupportReviewsRoute
  '/_authenticated/disputes/$disputeId': typeof AuthenticatedDisputesDisputeIdRoute
  '/_authenticated/seller-applications/$applicationId': typeof AuthenticatedSellerApplicationsApplicationIdRoute
  '/_authenticated/sellers/$sellerId': typeof AuthenticatedSellersSellerIdRoute
  '/_authenticated/avin-check/': typeof AuthenticatedAvinCheckIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/disputes/': typeof AuthenticatedDisputesIndexRoute
  '/_authenticated/listings/': typeof AuthenticatedListingsIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/operations/': typeof AuthenticatedOperationsIndexRoute
  '/_authenticated/seller-applications/': typeof AuthenticatedSellerApplicationsIndexRoute
  '/_authenticated/sellers/': typeof AuthenticatedSellersIndexRoute
  '/_authenticated/withdrawals/': typeof AuthenticatedWithdrawalsIndexRoute
  '/_authenticated/avin-check/provider-revisions/$revisionId': typeof AuthenticatedAvinCheckProviderRevisionsRevisionIdRoute
  '/_authenticated/avin-check/providers/$applicationId': typeof AuthenticatedAvinCheckProvidersApplicationIdRoute
  '/_authenticated/avin-check/risk-reports/$reportId': typeof AuthenticatedAvinCheckRiskReportsReportIdRoute
  '/_authenticated/avin-check/provider-revisions/': typeof AuthenticatedAvinCheckProviderRevisionsIndexRoute
  '/_authenticated/avin-check/providers/': typeof AuthenticatedAvinCheckProvidersIndexRoute
  '/_authenticated/avin-check/risk-reports/': typeof AuthenticatedAvinCheckRiskReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/two-factor'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/avin-check'
    | '/settings'
    | '/avin-check/bond'
    | '/avin-check/bond-withdrawals'
    | '/avin-check/support-reviews'
    | '/disputes/$disputeId'
    | '/seller-applications/$applicationId'
    | '/sellers/$sellerId'
    | '/avin-check/'
    | '/categories/'
    | '/disputes/'
    | '/listings/'
    | '/notifications/'
    | '/operations/'
    | '/seller-applications/'
    | '/sellers/'
    | '/withdrawals/'
    | '/avin-check/provider-revisions/$revisionId'
    | '/avin-check/providers/$applicationId'
    | '/avin-check/risk-reports/$reportId'
    | '/avin-check/provider-revisions/'
    | '/avin-check/providers/'
    | '/avin-check/risk-reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/two-factor'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/settings'
    | '/'
    | '/avin-check/bond'
    | '/avin-check/bond-withdrawals'
    | '/avin-check/support-reviews'
    | '/disputes/$disputeId'
    | '/seller-applications/$applicationId'
    | '/sellers/$sellerId'
    | '/avin-check'
    | '/categories'
    | '/disputes'
    | '/listings'
    | '/notifications'
    | '/operations'
    | '/seller-applications'
    | '/sellers'
    | '/withdrawals'
    | '/avin-check/provider-revisions/$revisionId'
    | '/avin-check/providers/$applicationId'
    | '/avin-check/risk-reports/$reportId'
    | '/avin-check/provider-revisions'
    | '/avin-check/providers'
    | '/avin-check/risk-reports'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sign-in'
    | '/two-factor'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/avin-check'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/avin-check/bond'
    | '/_authenticated/avin-check/bond-withdrawals'
    | '/_authenticated/avin-check/support-reviews'
    | '/_authenticated/disputes/$disputeId'
    | '/_authenticated/seller-applications/$applicationId'
    | '/_authenticated/sellers/$sellerId'
    | '/_authenticated/avin-check/'
    | '/_authenticated/categories/'
    | '/_authenticated/disputes/'
    | '/_authenticated/listings/'
    | '/_authenticated/notifications/'
    | '/_authenticated/operations/'
    | '/_authenticated/seller-applications/'
    | '/_authenticated/sellers/'
    | '/_authenticated/withdrawals/'
    | '/_authenticated/avin-check/provider-revisions/$revisionId'
    | '/_authenticated/avin-check/providers/$applicationId'
    | '/_authenticated/avin-check/risk-reports/$reportId'
    | '/_authenticated/avin-check/provider-revisions/'
    | '/_authenticated/avin-check/providers/'
    | '/_authenticated/avin-check/risk-reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  TwoFactorRoute: typeof TwoFactorRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/avin-check': {
      id: '/_authenticated/avin-check'
      path: '/avin-check'
      fullPath: '/avin-check'
      preLoaderRoute: typeof AuthenticatedAvinCheckRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/avin-check/': {
      id: '/_authenticated/avin-check/'
      path: '/'
      fullPath: '/avin-check/'
      preLoaderRoute: typeof AuthenticatedAvinCheckIndexRouteImport
      parentRoute: typeof AuthenticatedAvinCheckRoute
    }
    '/_authenticated/avin-check/bond': {
      id: '/_authenticated/avin-check/bond'
      path: '/bond'
      fullPath: '/avin-check/bond'
      preLoaderRoute: typeof AuthenticatedAvinCheckBondRouteImport
      parentRoute: typeof AuthenticatedAvinCheckRoute
    }
    '/_authenticated/avin-check/bond-withdrawals': {
      id: '/_authenticated/avin-check/bond-withdrawals'
      path: '/bond-withdrawals'
      fullPath: '/avin-check/bond-withdrawals'
      preLoaderRoute: typeof AuthenticatedAvinCheckBondWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAvinCheckRoute
    }
    '/_authenticated/avin-check/support-reviews': {
      id: '/_authenticated/avin-check/support-reviews'
      path: '/support-reviews'
      fullPath: '/avin-check/support-reviews'
      preLoaderRoute: typeof AuthenticatedAvinCheckSupportReviewsRouteImport
      parentRoute: typeof AuthenticatedAvinCheckRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disputes/': {
      id: '/_authenticated/disputes/'
      path: '/disputes'
      fullPath: '/disputes/'
      preLoaderRoute: typeof AuthenticatedDisputesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disputes/$disputeId': {
      id: '/_authenticated/disputes/$disputeId'
      path: '/disputes/$disputeId'
      fullPath: '/disputes/$disputeId'
      preLoaderRoute: typeof AuthenticatedDisputesDisputeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listings/': {
      id: '/_authenticated/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof AuthenticatedListingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations/': {
      id: '/_authenticated/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof AuthenticatedOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seller-applications/': {
      id: '/_authenticated/seller-applications/'
      path: '/seller-applications'
      fullPath: '/seller-applications/'
      preLoaderRoute: typeof AuthenticatedSellerApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seller-applications/$applicationId': {
      id: '/_authenticated/seller-applications/$applicationId'
      path: '/seller-applications/$applicationId'
      fullPath: '/seller-applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedSellerApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sellers/': {
      id: '/_authenticated/sellers/'
      path: '/sellers'
      fullPath: '/sellers/'
      preLoaderRoute: typeof AuthenticatedSellersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sellers/$sellerId': {
      id: '/_authenticated/sellers/$sellerId'
      path: '/sellers/$sellerId'
      fullPath: '/sellers/$sellerId'
      preLoaderRoute: typeof AuthenticatedSellersSellerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/withdrawals/': {
      id: '/_authenticated/withdrawals/'
      path: '/withdrawals'
      fullPath: '/withdrawals/'
      preLoaderRoute: typeof AuthenticatedWithdrawalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/avin-check/provider-revisions/': {
      id: '/_authenticated/avin-check/provider-revisions/'
      path: '/provider-revisions'
      fullPath: '/avin-check/provider-revisions/'
      preLoaderRoute: typeof AuthenticatedAvinCheckProviderRevisionsIndexRouteImport
      parentRoute: typeof AuthenticatedAvinCheckRoute
    }
    '/_authenticated/avin-check/provider-revisions/$revisionId': {
      id: '/_authenticated/avin-check/provider-revisions/$revisionId'
      path: '/provider-revisions/$revisionId'
      fullPath: '/avin-check/provider-revisions/$revisionId'
      preLoaderRoute: typeof AuthenticatedAvinCheckProviderRevisionsRevisionIdRouteImport
      parentRoute: typeof AuthenticatedAvinCheckRoute
    }
    '/_authenticated/avin-check/providers/': {
      id: '/_authenticated/avin-check/providers/'
      path: '/providers'
      fullPath: '/avin-check/providers/'
      preLoaderRoute: typeof AuthenticatedAvinCheckProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedAvinCheckRoute
    }
    '/_authenticated/avin-check/providers/$applicationId': {
      id: '/_authenticated/avin-check/providers/$applicationId'
      path: '/providers/$applicationId'
      fullPath: '/avin-check/providers/$applicationId'
      preLoaderRoute: typeof AuthenticatedAvinCheckProvidersApplicationIdRouteImport
      parentRoute: typeof AuthenticatedAvinCheckRoute
    }
    '/_authenticated/avin-check/risk-reports/': {
      id: '/_authenticated/avin-check/risk-reports/'
      path: '/risk-reports'
      fullPath: '/avin-check/risk-reports/'
      preLoaderRoute: typeof AuthenticatedAvinCheckRiskReportsIndexRouteImport
      parentRoute: typeof AuthenticatedAvinCheckRoute
    }
    '/_authenticated/avin-check/risk-reports/$reportId': {
      id: '/_authenticated/avin-check/risk-reports/$reportId'
      path: '/risk-reports/$reportId'
      fullPath: '/avin-check/risk-reports/$reportId'
      preLoaderRoute: typeof AuthenticatedAvinCheckRiskReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedAvinCheckRoute
    }
  }
}

interface AuthenticatedAvinCheckRouteChildren {
  AuthenticatedAvinCheckBondRoute: typeof AuthenticatedAvinCheckBondRoute
  AuthenticatedAvinCheckBondWithdrawalsRoute: typeof AuthenticatedAvinCheckBondWithdrawalsRoute
  AuthenticatedAvinCheckSupportReviewsRoute: typeof AuthenticatedAvinCheckSupportReviewsRoute
  AuthenticatedAvinCheckIndexRoute: typeof AuthenticatedAvinCheckIndexRoute
  AuthenticatedAvinCheckProviderRevisionsRevisionIdRoute: typeof AuthenticatedAvinCheckProviderRevisionsRevisionIdRoute
  AuthenticatedAvinCheckProvidersApplicationIdRoute: typeof AuthenticatedAvinCheckProvidersApplicationIdRoute
  AuthenticatedAvinCheckRiskReportsReportIdRoute: typeof AuthenticatedAvinCheckRiskReportsReportIdRoute
  AuthenticatedAvinCheckProviderRevisionsIndexRoute: typeof AuthenticatedAvinCheckProviderRevisionsIndexRoute
  AuthenticatedAvinCheckProvidersIndexRoute: typeof AuthenticatedAvinCheckProvidersIndexRoute
  AuthenticatedAvinCheckRiskReportsIndexRoute: typeof AuthenticatedAvinCheckRiskReportsIndexRoute
}

const AuthenticatedAvinCheckRouteChildren: AuthenticatedAvinCheckRouteChildren =
  {
    AuthenticatedAvinCheckBondRoute: AuthenticatedAvinCheckBondRoute,
    AuthenticatedAvinCheckBondWithdrawalsRoute:
      AuthenticatedAvinCheckBondWithdrawalsRoute,
    AuthenticatedAvinCheckSupportReviewsRoute:
      AuthenticatedAvinCheckSupportReviewsRoute,
    AuthenticatedAvinCheckIndexRoute: AuthenticatedAvinCheckIndexRoute,
    AuthenticatedAvinCheckProviderRevisionsRevisionIdRoute:
      AuthenticatedAvinCheckProviderRevisionsRevisionIdRoute,
    AuthenticatedAvinCheckProvidersApplicationIdRoute:
      AuthenticatedAvinCheckProvidersApplicationIdRoute,
    AuthenticatedAvinCheckRiskReportsReportIdRoute:
      AuthenticatedAvinCheckRiskReportsReportIdRoute,
    AuthenticatedAvinCheckProviderRevisionsIndexRoute:
      AuthenticatedAvinCheckProviderRevisionsIndexRoute,
    AuthenticatedAvinCheckProvidersIndexRoute:
      AuthenticatedAvinCheckProvidersIndexRoute,
    AuthenticatedAvinCheckRiskReportsIndexRoute:
      AuthenticatedAvinCheckRiskReportsIndexRoute,
  }

const AuthenticatedAvinCheckRouteWithChildren =
  AuthenticatedAvinCheckRoute._addFileChildren(
    AuthenticatedAvinCheckRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAvinCheckRoute: typeof AuthenticatedAvinCheckRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDisputesDisputeIdRoute: typeof AuthenticatedDisputesDisputeIdRoute
  AuthenticatedSellerApplicationsApplicationIdRoute: typeof AuthenticatedSellerApplicationsApplicationIdRoute
  AuthenticatedSellersSellerIdRoute: typeof AuthenticatedSellersSellerIdRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedDisputesIndexRoute: typeof AuthenticatedDisputesIndexRoute
  AuthenticatedListingsIndexRoute: typeof AuthenticatedListingsIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedOperationsIndexRoute: typeof AuthenticatedOperationsIndexRoute
  AuthenticatedSellerApplicationsIndexRoute: typeof AuthenticatedSellerApplicationsIndexRoute
  AuthenticatedSellersIndexRoute: typeof AuthenticatedSellersIndexRoute
  AuthenticatedWithdrawalsIndexRoute: typeof AuthenticatedWithdrawalsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAvinCheckRoute: AuthenticatedAvinCheckRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDisputesDisputeIdRoute: AuthenticatedDisputesDisputeIdRoute,
  AuthenticatedSellerApplicationsApplicationIdRoute:
    AuthenticatedSellerApplicationsApplicationIdRoute,
  AuthenticatedSellersSellerIdRoute: AuthenticatedSellersSellerIdRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedDisputesIndexRoute: AuthenticatedDisputesIndexRoute,
  AuthenticatedListingsIndexRoute: AuthenticatedListingsIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedOperationsIndexRoute: AuthenticatedOperationsIndexRoute,
  AuthenticatedSellerApplicationsIndexRoute:
    AuthenticatedSellerApplicationsIndexRoute,
  AuthenticatedSellersIndexRoute: AuthenticatedSellersIndexRoute,
  AuthenticatedWithdrawalsIndexRoute: AuthenticatedWithdrawalsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  TwoFactorRoute: TwoFactorRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
