/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as DisputesIndexRouteImport } from './routes/disputes/index'
import { Route as DisputesDisputeIdRouteImport } from './routes/disputes/$disputeId'
import { Route as SellerApplicationsIndexRouteImport } from './routes/seller-applications/index'
import { Route as SellerApplicationsApplicationIdRouteImport } from './routes/seller-applications/$applicationId'
import { Route as SellersIndexRouteImport } from './routes/sellers/index'
import { Route as SellersSellerIdRouteImport } from './routes/sellers/$sellerId'
import { Route as WithdrawalsIndexRouteImport } from './routes/withdrawals/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesIndexRoute = DisputesIndexRouteImport.update({
  id: '/disputes/',
  path: '/disputes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesDisputeIdRoute = DisputesDisputeIdRouteImport.update({
  id: '/disputes/$disputeId',
  path: '/disputes/$disputeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerApplicationsIndexRoute = SellerApplicationsIndexRouteImport.update({
  id: '/seller-applications/',
  path: '/seller-applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerApplicationsApplicationIdRoute =
  SellerApplicationsApplicationIdRouteImport.update({
    id: '/seller-applications/$applicationId',
    path: '/seller-applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SellersIndexRoute = SellersIndexRouteImport.update({
  id: '/sellers/',
  path: '/sellers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersSellerIdRoute = SellersSellerIdRouteImport.update({
  id: '/sellers/$sellerId',
  path: '/sellers/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalsIndexRoute = WithdrawalsIndexRouteImport.update({
  id: '/withdrawals/',
  path: '/withdrawals/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/seller-applications/$applicationId': typeof SellerApplicationsApplicationIdRoute
  '/sellers/$sellerId': typeof SellersSellerIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/disputes/': typeof DisputesIndexRoute
  '/seller-applications/': typeof SellerApplicationsIndexRoute
  '/sellers/': typeof SellersIndexRoute
  '/withdrawals/': typeof WithdrawalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/seller-applications/$applicationId': typeof SellerApplicationsApplicationIdRoute
  '/sellers/$sellerId': typeof SellersSellerIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/disputes': typeof DisputesIndexRoute
  '/seller-applications': typeof SellerApplicationsIndexRoute
  '/sellers': typeof SellersIndexRoute
  '/withdrawals': typeof WithdrawalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/seller-applications/$applicationId': typeof SellerApplicationsApplicationIdRoute
  '/sellers/$sellerId': typeof SellersSellerIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/disputes/': typeof DisputesIndexRoute
  '/seller-applications/': typeof SellerApplicationsIndexRoute
  '/sellers/': typeof SellersIndexRoute
  '/withdrawals/': typeof WithdrawalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disputes/$disputeId'
    | '/seller-applications/$applicationId'
    | '/sellers/$sellerId'
    | '/categories/'
    | '/disputes/'
    | '/seller-applications/'
    | '/sellers/'
    | '/withdrawals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disputes/$disputeId'
    | '/seller-applications/$applicationId'
    | '/sellers/$sellerId'
    | '/categories'
    | '/disputes'
    | '/seller-applications'
    | '/sellers'
    | '/withdrawals'
  id:
    | '__root__'
    | '/'
    | '/disputes/$disputeId'
    | '/seller-applications/$applicationId'
    | '/sellers/$sellerId'
    | '/categories/'
    | '/disputes/'
    | '/seller-applications/'
    | '/sellers/'
    | '/withdrawals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisputesDisputeIdRoute: typeof DisputesDisputeIdRoute
  SellerApplicationsApplicationIdRoute: typeof SellerApplicationsApplicationIdRoute
  SellersSellerIdRoute: typeof SellersSellerIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  DisputesIndexRoute: typeof DisputesIndexRoute
  SellerApplicationsIndexRoute: typeof SellerApplicationsIndexRoute
  SellersIndexRoute: typeof SellersIndexRoute
  WithdrawalsIndexRoute: typeof WithdrawalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes/': {
      id: '/disputes/'
      path: '/disputes'
      fullPath: '/disputes/'
      preLoaderRoute: typeof DisputesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes/$disputeId': {
      id: '/disputes/$disputeId'
      path: '/disputes/$disputeId'
      fullPath: '/disputes/$disputeId'
      preLoaderRoute: typeof DisputesDisputeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-applications/': {
      id: '/seller-applications/'
      path: '/seller-applications'
      fullPath: '/seller-applications/'
      preLoaderRoute: typeof SellerApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-applications/$applicationId': {
      id: '/seller-applications/$applicationId'
      path: '/seller-applications/$applicationId'
      fullPath: '/seller-applications/$applicationId'
      preLoaderRoute: typeof SellerApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/': {
      id: '/sellers/'
      path: '/sellers'
      fullPath: '/sellers/'
      preLoaderRoute: typeof SellersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/$sellerId': {
      id: '/sellers/$sellerId'
      path: '/sellers/$sellerId'
      fullPath: '/sellers/$sellerId'
      preLoaderRoute: typeof SellersSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawals/': {
      id: '/withdrawals/'
      path: '/withdrawals'
      fullPath: '/withdrawals/'
      preLoaderRoute: typeof WithdrawalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisputesDisputeIdRoute: DisputesDisputeIdRoute,
  SellerApplicationsApplicationIdRoute: SellerApplicationsApplicationIdRoute,
  SellersSellerIdRoute: SellersSellerIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  DisputesIndexRoute: DisputesIndexRoute,
  SellerApplicationsIndexRoute: SellerApplicationsIndexRoute,
  SellersIndexRoute: SellersIndexRoute,
  WithdrawalsIndexRoute: WithdrawalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
