/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedTwoFactorRouteImport } from './routes/_authenticated/two-factor'
import { Route as authSellerLoginRouteImport } from './routes/(auth)/seller/login'
import { Route as publicCategoryIndexRouteImport } from './routes/(public)/category/index'
import { Route as publicCategoryParentSlugRouteImport } from './routes/(public)/category/$parentSlug'
import { Route as publicListingIdRouteImport } from './routes/(public)/listing/$id'
import { Route as publicStoreSlugRouteImport } from './routes/(public)/store/$slug'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders/$id'
import { Route as AuthenticatedSellerListingsRouteImport } from './routes/_authenticated/seller/listings'
import { Route as AuthenticatedSellerOnboardingRouteImport } from './routes/_authenticated/seller/onboarding'
import { Route as AuthenticatedSellerStoreRouteImport } from './routes/_authenticated/seller/store'
import { Route as AuthenticatedSellerStorePreviewRouteImport } from './routes/_authenticated/seller/store-preview'
import { Route as AuthenticatedWalletIndexRouteImport } from './routes/_authenticated/wallet/index'
import { Route as AuthenticatedWalletDepositRouteImport } from './routes/_authenticated/wallet/deposit'
import { Route as AuthenticatedSellerListingsIdRouteImport } from './routes/_authenticated/seller/listings/$id'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTwoFactorRoute = AuthenticatedTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSellerLoginRoute = authSellerLoginRouteImport.update({
  id: '/seller/login',
  path: '/seller/login',
  getParentRoute: () => authRouteRoute,
} as any)
const publicCategoryIndexRoute = publicCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicCategoryParentSlugRoute =
  publicCategoryParentSlugRouteImport.update({
    id: '/category/$parentSlug',
    path: '/category/$parentSlug',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicListingIdRoute = publicListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicStoreSlugRoute = publicStoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => publicRouteRoute,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerListingsRoute =
  AuthenticatedSellerListingsRouteImport.update({
    id: '/seller/listings',
    path: '/seller/listings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellerOnboardingRoute =
  AuthenticatedSellerOnboardingRouteImport.update({
    id: '/seller/onboarding',
    path: '/seller/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellerStoreRoute =
  AuthenticatedSellerStoreRouteImport.update({
    id: '/seller/store',
    path: '/seller/store',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellerStorePreviewRoute =
  AuthenticatedSellerStorePreviewRouteImport.update({
    id: '/seller/store-preview',
    path: '/seller/store-preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletIndexRoute =
  AuthenticatedWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletDepositRoute =
  AuthenticatedWalletDepositRouteImport.update({
    id: '/wallet/deposit',
    path: '/wallet/deposit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellerListingsIdRoute =
  AuthenticatedSellerListingsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSellerListingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/login': typeof authLoginRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/ai': typeof AuthenticatedAiRoute
  '/cart': typeof AuthenticatedCartRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/two-factor': typeof AuthenticatedTwoFactorRoute
  '/seller/login': typeof authSellerLoginRoute
  '/category/$parentSlug': typeof publicCategoryParentSlugRoute
  '/listing/$id': typeof publicListingIdRoute
  '/store/$slug': typeof publicStoreSlugRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/seller/listings': typeof AuthenticatedSellerListingsRouteWithChildren
  '/seller/onboarding': typeof AuthenticatedSellerOnboardingRoute
  '/seller/store': typeof AuthenticatedSellerStoreRoute
  '/seller/store-preview': typeof AuthenticatedSellerStorePreviewRoute
  '/wallet/deposit': typeof AuthenticatedWalletDepositRoute
  '/category/': typeof publicCategoryIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/wallet/': typeof AuthenticatedWalletIndexRoute
  '/seller/listings/$id': typeof AuthenticatedSellerListingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/login': typeof authLoginRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/ai': typeof AuthenticatedAiRoute
  '/cart': typeof AuthenticatedCartRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/two-factor': typeof AuthenticatedTwoFactorRoute
  '/seller/login': typeof authSellerLoginRoute
  '/category/$parentSlug': typeof publicCategoryParentSlugRoute
  '/listing/$id': typeof publicListingIdRoute
  '/store/$slug': typeof publicStoreSlugRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/seller/listings': typeof AuthenticatedSellerListingsRouteWithChildren
  '/seller/onboarding': typeof AuthenticatedSellerOnboardingRoute
  '/seller/store': typeof AuthenticatedSellerStoreRoute
  '/seller/store-preview': typeof AuthenticatedSellerStorePreviewRoute
  '/wallet/deposit': typeof AuthenticatedWalletDepositRoute
  '/category': typeof publicCategoryIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
  '/seller/listings/$id': typeof AuthenticatedSellerListingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/two-factor': typeof AuthenticatedTwoFactorRoute
  '/(public)/': typeof publicIndexRoute
  '/(auth)/seller/login': typeof authSellerLoginRoute
  '/(public)/category/$parentSlug': typeof publicCategoryParentSlugRoute
  '/(public)/listing/$id': typeof publicListingIdRoute
  '/(public)/store/$slug': typeof publicStoreSlugRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/seller/listings': typeof AuthenticatedSellerListingsRouteWithChildren
  '/_authenticated/seller/onboarding': typeof AuthenticatedSellerOnboardingRoute
  '/_authenticated/seller/store': typeof AuthenticatedSellerStoreRoute
  '/_authenticated/seller/store-preview': typeof AuthenticatedSellerStorePreviewRoute
  '/_authenticated/wallet/deposit': typeof AuthenticatedWalletDepositRoute
  '/(public)/category/': typeof publicCategoryIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
  '/_authenticated/seller/listings/$id': typeof AuthenticatedSellerListingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/ai'
    | '/cart'
    | '/security'
    | '/two-factor'
    | '/seller/login'
    | '/category/$parentSlug'
    | '/listing/$id'
    | '/store/$slug'
    | '/orders/$id'
    | '/seller/listings'
    | '/seller/onboarding'
    | '/seller/store'
    | '/seller/store-preview'
    | '/wallet/deposit'
    | '/category/'
    | '/orders/'
    | '/wallet/'
    | '/seller/listings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/ai'
    | '/cart'
    | '/security'
    | '/two-factor'
    | '/seller/login'
    | '/category/$parentSlug'
    | '/listing/$id'
    | '/store/$slug'
    | '/orders/$id'
    | '/seller/listings'
    | '/seller/onboarding'
    | '/seller/store'
    | '/seller/store-preview'
    | '/wallet/deposit'
    | '/category'
    | '/orders'
    | '/wallet'
    | '/seller/listings/$id'
  id:
    | '__root__'
    | '/(auth)'
    | '/(public)'
    | '/_authenticated'
    | '/(auth)/login'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/ai'
    | '/_authenticated/cart'
    | '/_authenticated/security'
    | '/_authenticated/two-factor'
    | '/(public)/'
    | '/(auth)/seller/login'
    | '/(public)/category/$parentSlug'
    | '/(public)/listing/$id'
    | '/(public)/store/$slug'
    | '/_authenticated/orders/$id'
    | '/_authenticated/seller/listings'
    | '/_authenticated/seller/onboarding'
    | '/_authenticated/seller/store'
    | '/_authenticated/seller/store-preview'
    | '/_authenticated/wallet/deposit'
    | '/(public)/category/'
    | '/_authenticated/orders/'
    | '/_authenticated/wallet/'
    | '/_authenticated/seller/listings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/two-factor': {
      id: '/_authenticated/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof AuthenticatedTwoFactorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/seller/login': {
      id: '/(auth)/seller/login'
      path: '/seller/login'
      fullPath: '/seller/login'
      preLoaderRoute: typeof authSellerLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(public)/category/': {
      id: '/(public)/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof publicCategoryIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/category/$parentSlug': {
      id: '/(public)/category/$parentSlug'
      path: '/category/$parentSlug'
      fullPath: '/category/$parentSlug'
      preLoaderRoute: typeof publicCategoryParentSlugRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/listing/$id': {
      id: '/(public)/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof publicListingIdRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/store/$slug': {
      id: '/(public)/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof publicStoreSlugRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/listings': {
      id: '/_authenticated/seller/listings'
      path: '/seller/listings'
      fullPath: '/seller/listings'
      preLoaderRoute: typeof AuthenticatedSellerListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/onboarding': {
      id: '/_authenticated/seller/onboarding'
      path: '/seller/onboarding'
      fullPath: '/seller/onboarding'
      preLoaderRoute: typeof AuthenticatedSellerOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/store': {
      id: '/_authenticated/seller/store'
      path: '/seller/store'
      fullPath: '/seller/store'
      preLoaderRoute: typeof AuthenticatedSellerStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/store-preview': {
      id: '/_authenticated/seller/store-preview'
      path: '/seller/store-preview'
      fullPath: '/seller/store-preview'
      preLoaderRoute: typeof AuthenticatedSellerStorePreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AuthenticatedWalletIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/deposit': {
      id: '/_authenticated/wallet/deposit'
      path: '/wallet/deposit'
      fullPath: '/wallet/deposit'
      preLoaderRoute: typeof AuthenticatedWalletDepositRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/listings/$id': {
      id: '/_authenticated/seller/listings/$id'
      path: '/$id'
      fullPath: '/seller/listings/$id'
      preLoaderRoute: typeof AuthenticatedSellerListingsIdRouteImport
      parentRoute: typeof AuthenticatedSellerListingsRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSellerLoginRoute: typeof authSellerLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSellerLoginRoute: authSellerLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicCategoryParentSlugRoute: typeof publicCategoryParentSlugRoute
  publicListingIdRoute: typeof publicListingIdRoute
  publicStoreSlugRoute: typeof publicStoreSlugRoute
  publicCategoryIndexRoute: typeof publicCategoryIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicCategoryParentSlugRoute: publicCategoryParentSlugRoute,
  publicListingIdRoute: publicListingIdRoute,
  publicStoreSlugRoute: publicStoreSlugRoute,
  publicCategoryIndexRoute: publicCategoryIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface AuthenticatedSellerListingsRouteChildren {
  AuthenticatedSellerListingsIdRoute: typeof AuthenticatedSellerListingsIdRoute
}

const AuthenticatedSellerListingsRouteChildren: AuthenticatedSellerListingsRouteChildren =
  {
    AuthenticatedSellerListingsIdRoute: AuthenticatedSellerListingsIdRoute,
  }

const AuthenticatedSellerListingsRouteWithChildren =
  AuthenticatedSellerListingsRoute._addFileChildren(
    AuthenticatedSellerListingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedTwoFactorRoute: typeof AuthenticatedTwoFactorRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedSellerListingsRoute: typeof AuthenticatedSellerListingsRouteWithChildren
  AuthenticatedSellerOnboardingRoute: typeof AuthenticatedSellerOnboardingRoute
  AuthenticatedSellerStoreRoute: typeof AuthenticatedSellerStoreRoute
  AuthenticatedSellerStorePreviewRoute: typeof AuthenticatedSellerStorePreviewRoute
  AuthenticatedWalletDepositRoute: typeof AuthenticatedWalletDepositRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedTwoFactorRoute: AuthenticatedTwoFactorRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedSellerListingsRoute:
    AuthenticatedSellerListingsRouteWithChildren,
  AuthenticatedSellerOnboardingRoute: AuthenticatedSellerOnboardingRoute,
  AuthenticatedSellerStoreRoute: AuthenticatedSellerStoreRoute,
  AuthenticatedSellerStorePreviewRoute: AuthenticatedSellerStorePreviewRoute,
  AuthenticatedWalletDepositRoute: AuthenticatedWalletDepositRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
